#ifndef CONFIG_H
#define CONFIG_H

/*
 * Global kernel configuration knobs.
 * Adjusting these values enables stress and scalability testing without
 * having to patch core kernel sources.
 */
#define CONFIG_MAX_PROCS          32
#define CONFIG_PROC_STACK_SIZE    4096
#define CONFIG_MSG_QUEUE_LEN      16
#define CONFIG_MSG_DATA_MAX       256
#define CONFIG_IPC_MAX_CHANNELS   32
#define CONFIG_IPC_CHANNEL_QUEUE_LEN 32
#define CONFIG_IPC_CHANNEL_NAME_MAX 32
#define CONFIG_IPC_CHANNEL_SUBSCRIBERS 8
#define CONFIG_IPC_CHANNEL_WAITERS 8
#define CONFIG_PROCESS_CHANNEL_SLOTS 8
#define CONFIG_IPC_PAGE_SIZE        4096
#define CONFIG_IPC_CAPACITY_PER_PROC 16
#define CONFIG_IPC_MAX_SHARED_REGIONS 64
#define CONFIG_IPC_MAX_SHARED_PER_PROC 8
#define CONFIG_IPC_ENDPOINT_WAITERS 8

#define CONFIG_KLOG_CAPACITY      128
#define CONFIG_KLOG_ENTRY_LEN     96
#define CONFIG_KLOG_DEFAULT_LEVEL 1
#define CONFIG_KLOG_MODULE_NAME_LEN 24
#define CONFIG_KLOG_MAX_MODULES   32

#define CONFIG_CONSOLE_MAX_ROWS    64
#define CONFIG_CONSOLE_MAX_COLS    160

#define CONFIG_SCHED_PRIORITY_LEVELS    4
#define CONFIG_SCHED_DEFAULT_TIMESLICE   4
#define CONFIG_SCHED_MAX_DYNAMIC_BOOST   1
#define CONFIG_SCHED_MIN_PRIORITY        0
#define CONFIG_SCHED_BASE_WEIGHT         1024u
#define CONFIG_SCHED_DEFAULT_WEIGHT      1024u

#define CONFIG_SYNC_MAX_MUTEXES          32
#define CONFIG_SYNC_MAX_SEMAPHORES       32
#define CONFIG_SYNC_MAX_WAITERS          8

#define CONFIG_STRESS_SPIN_CYCLES 5000

#define CONFIG_USER_SPACE_LIMIT 0x80000000u

#define CONFIG_SECURITY_MAX_USERS    16
#define CONFIG_SECURITY_MAX_SESSIONS 16

#endif
